server:
  address: ${GATEWAY_ADDRESS:127.0.0.1}
  port: ${GATEWAY_PORT:8090}
  shutdown: graceful

spring:
  application:
    name: orderflow-gateway
  web:
    error:
      include-message: never
      include-stacktrace: never
  lifecycle:
    timeout-per-shutdown-phase: 10s
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 3s
          routes:
            - id: orderflow-products
              uri: ${ORDERFLOW_URL:http://127.0.0.1:8080}
              predicates:
                - Path=/api/products,/api/products/**
            - id: orderflow-orders
              uri: ${ORDERFLOW_URL:http://127.0.0.1:8080}
              predicates:
                - Path=/api/orders,/api/orders/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
